baseURL = "https://stt4230.rbind.io/"
languageCode = "fr-ca"
DefaultContentLanguage = "fr"

title = "STT-4230"
theme = "hugo-theme-docdock"
themesdir = "themes/"

googleAnalytics = "UA-111222298-1"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
  
[params]
editURL = "https://github.com/sophieb/STT-4230/tree/master/content/"
showVisitedLinks = false # default is false
themeStyle = "original" # "original" or "flex" # default "original"
themeVariant = "blue" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = true # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window
enableGitInfo = true

description = "Notes du cours STT-4230 / STT-6230 R pour scientifique"

[taxonomies]
category = "categories"
  
[permalinks]
post = "/:slug/"
    
[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
pre = "<h4></h4>"
name = "<i class='fa fa-calendar'></i> Classement par date du cours"
url = "/categories/"
weight = 1   

[[menu.shortcuts]]
pre = "<h4></h4>"
name = "<i class='fa fa-github'></i> Dépôt Github"
url = "https://github.com/sophieb/STT-4230"
weight = 2
