baseURL = "https://stt4230.netlify.com/"
languageCode = "en-us"
DefaultContentLanguage = "fr"

title = "STT-4230"
theme = "hugo-theme-docdock"
themesdir = "themes/"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
  
[params]
showVisitedLinks = false # default is false
themeStyle = "original" # "original" or "flex" # default "original"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
pre = "<h3></h3>"
name = "<i class='fa fa-github'></i> Dépôt Github"
identifier = "ds"
url = "https://github.com/sophieb/STT-4230"
weight = 11
